Implement migrate

diff --git a/vpn/setup-vpnd b/vpn/setup-vpnd
--- a/vpn/setup-vpnd
+++ b/vpn/setup-vpnd
@@ -29,7 +29,9 @@ function stop_vpnd(){
     if [ -x "$SA" ]; then
         $SA stop vpn >> $LOG 2>&1
     fi
+    killall -HUP vpnd
     launchctl disable $service_domain >> $LOG 2>&1
+    launchctl unload -w $service_domain >> $LOG 2>&1
 }
 
 iam=`basename "$0"`
@@ -116,17 +118,25 @@ case $etype in
 
         ;;
     migrate )
-        #if [ -f "${LAUNCHDIR}/${LAUNCHPLIST}" ]; then
-        #    echo "VPN service is already configured."
-        #    echo "Abort!"
-        #    show_help
-        #    exit 1
-        #fi
+        if [ -f "${LAUNCHDIR}/${LAUNCHPLIST}" ]; then
+            echo "VPN service is already configured."
+            echo "Abort!"
+            show_help
+            exit 1
+        fi
         stop_vpnd
         cp "${TEMPDIR}/${LAUNCHPLIST}" "${LAUNCHDIR}/${LAUNCHPLIST}"
         chmod 644 "${LAUNCHDIR}/${LAUNCHPLIST}"
         chown 0:0 "${LAUNCHDIR}/${LAUNCHPLIST}"
-        launchctl load "${LAUNCHDIR}/${LAUNCHPLIST}"
-        echo "Type 'sudo vpndc start' to start your VPN service."
         ;;
 esac
+
+launchctl load -w "${LAUNCHDIR}/${LAUNCHPLIST}" > /dev/null 2>&1
+vpnstatus=`${pathtome}/vpndc status`
+if [ $vpnstatus = 'running' ]; then
+    echo "Good! Your VPN service is now ${vpnstatus}."
+    exit 0
+else
+    echo "Failed! Something wrong."
+    exit 1
+fi
