wip

diff --git a/vpn/vpnd-presharedkey b/vpn/vpnd-presharedkey
--- a/vpn/vpnd-presharedkey
+++ b/vpn/vpnd-presharedkey
@@ -21,8 +21,14 @@ function _readlink(){
 function show_help(){
     cat <<_HELP
 
-    $iam -s: Show preshared key for VPN service.
+Usage::
     $iam -c <preshared_key>: Replace preshared key with new one. If it is not set, set new one.
+    $iam -d: Delete preshared key.
+    $iam -h: Show this message.
+    $iam -s: Show preshared key for VPN service.
+
+Known bugs::
+    - If you create preshared key by kind of command like this script, replace preshared key with new one will be failed.
 
 _HELP
 }
@@ -43,7 +49,7 @@ if [ $# = 0 ]; then
 fi
 
 if [ `whoami` != root ]; then
-    echo "Use me with 'sudo'"
+    echo "You need administrator access to run this tool... exiting!"
     show_help
     exit 1
 fi
@@ -76,6 +82,12 @@ do
                     opt='-U -A'
                 fi
                 security add-generic-password $opt -s $SNAME -a $PSK_ACCOUNT -w "$NEW_PSK" "$KEYCHAIN"
+                rtn=$?
+                if [ $rtn -ne 0 ]; then
+                    echo "Failed to update preshared key."
+                    echo "Try to update it with Keychain Access.app"
+                    exit $rtn
+                fi
             else
                 echo "Not found ${CDIR}/${PNAME}" >&2
                 echo "VPN services is not configured yet" >&2
