Add file exist check

diff --git a/vpn/vpndc-car b/vpn/vpndc-car
--- a/vpn/vpndc-car
+++ b/vpn/vpndc-car
@@ -3,7 +3,6 @@
 iam=`basename "$0"`
 mode=show
 PNAME="/Library/Preferences/SystemConfiguration/com.apple.RemoteAccessServers.plist"
-MaximumSessions=`/usr/libexec/PlistBuddy -c "print Servers:com.apple.ppp.l2tp:Server:MaximumSessions" "$PNAME"`
 
 function _readlink(){
     f=`basename "$1"`
@@ -29,6 +28,15 @@ _HELP
 
 fullpath_to_me=`_readlink "$0"`
 pathtome="`dirname \"$fullpath_to_me\"`"
+
+if [ ! -f "$PNAME" ]; then
+    echo "Not found: $PNAME"
+    echo "This host is not configured yet."
+    show_help
+    exit 1
+fi
+
+MaximumSessions=`/usr/libexec/PlistBuddy -c "print Servers:com.apple.ppp.l2tp:Server:MaximumSessions" "$PNAME"`
 
 if [ $# = 0 ]; then
     show_help
diff --git a/vpn/vpndc-dns b/vpn/vpndc-dns
--- a/vpn/vpndc-dns
+++ b/vpn/vpndc-dns
@@ -29,6 +29,13 @@ _HELP
 fullpath_to_me=`_readlink "$0"`
 pathtome="`dirname \"$fullpath_to_me\"`"
 
+if [ ! -f "$PNAME" ]; then
+    echo "Not found: $PNAME"
+    echo "This host is not configured yet."
+    show_help
+    exit 1
+fi
+
 if [ $# = 0 ]; then
     show_help
     exit 1
diff --git a/vpn/vpndc-hostname b/vpn/vpndc-hostname
--- a/vpn/vpndc-hostname
+++ b/vpn/vpndc-hostname
@@ -14,24 +14,17 @@ Usage::
 _HELP
 }
 
-function _readlink(){
-    f=`basename "$1"`
-    d=`cd $(dirname "$1"); pwd`
-    if [ -L "${d}/${f}" ]; then
-        r="`readlink -n \"${d}/${f}\"`"
-        _readlink "$r"
-    else
-        echo "${d}/${f}"
-    fi
-}
+if [ ! -f "$PNAME" ]; then
+    echo "Not found: $PNAME"
+    echo "This host is not configured yet."
+    show_help
+    exit 1
+fi
 
 if [ $# = 0 ]; then
     show_help
     exit 1
 fi
-
-fullpath_to_me=`_readlink "$0"`
-pathtome="`dirname \"$fullpath_to_me\"`"
 
 while getopts hsS: sw
 do
@@ -45,9 +38,8 @@ do
                 show_help
                 exit 1
             fi
-            H=${OPTARG}
 
-            VPNHOST=$H
+            VPNHOST="${OPTARG}"
             /usr/libexec/PlistBuddy -c "delete VPNHost" "$PNAME" 2> /dev/null
             /usr/libexec/PlistBuddy -c "add VPNHost string $VPNHOST" "$PNAME"
             ;;
